# ------------------- #
# Website information #
# ------------------- #

title: Ryefield Society
owner: Ryefield Society Music
email: contact@ryefieldsociety.com
avatar: https://pbs.twimg.com/profile_images/1575519855003959296/JGxj9wOt_400x400.jpg
description: >- 
  Ryefield Society Music.
keywords: Ryefield, Society, Music, Ambient, Bandcamp, Independant, Experimental, postrock, French
site_inception: 2021-08-08
language: en
encoding: utf-8
theme-color: "#ffffff"

# ------------- #
# News settings #
# ------------- #

excerpt_separator: <!--more-->

# -------------- #
# Build settings #
# -------------- #

plugins:
  # Build RSS feed, see here: https://github.com/jekyll/jekyll-feed
  - jekyll-feed
  # Build search engine tags for seo, see here: https://github.com/jekyll/jekyll-seo-tag
  - jekyll-seo-tag
  # Build the sitemap, see here: https://github.com/jekyll/jekyll-sitemap
  - jekyll-sitemap

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
