# ------------------- #
# Website information #
# ------------------- #

title: Ryefield Society
owner: Ryefield Society Music
email: ryefieldsociety@gmail.com
avatar: https://f4.bcbits.com/img/0023280376_10.jpg
description: >- 
  Ryefield Society Music.
keywords: Ryefield, Society, Music, Ambient, Bandcamp, Independant, Experimental, French
url: "https://RyefieldSociety.com"
site_inception:
  year: 2021
  month: 8
  day: 8
language: en
encoding: utf-8
theme-color: "#ffffff"

# ------------- #
# News settings #
# ------------- #

excerpt_separator: <!--more-->

# -------------- #
# Build settings #
# -------------- #

plugins:
  # Build RSS feed, see here: https://github.com/jekyll/jekyll-feed
  - jekyll-feed
  # Build search engine tags for indexing, see here: https://github.com/jekyll/jekyll-seo-tag
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
